apiVersion: v1
kind: Namespace
metadata: 
  name: demo
---
kind: Service
apiVersion: v1
metadata:
  name: demo-webapp
  namespace: demo
spec:
  selector:
    app: demo-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webapp
  namespace: demo
  labels:
    app: demo-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-webapp
  template:
    metadata:
      labels:
        app: demo-webapp
    spec:
      containers:
      - name: demo-webapp
        image: chvarun22/docker:0.1.114
        ports:
        - containerPort: 80
