apiVersion: v1
kind: Namespace
metadata: 
  name: demo:0.1.358
---
kind: Service
apiVersion: v1
metadata:
  name: demo:0.1.358
  namespace: demo:0.1.358
spec:
  selector:
    app: demo:0.1.358
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo:0.1.358
  namespace: demo:0.1.358
  labels:
    app: demo:0.1.358
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo:0.1.358
  template:
    metadata:
      labels:
        app: demo:0.1.358
    spec:
      containers:
      - name: demo:0.1.358
        image: chvarun22/docker:$TAG
        ports:
        - containerPort: 80
