apiVersion: v1
kind: Namespace
metadata: 
  name: demo
---
kind: Service
apiVersion: v1
metadata:
  name: demo-webapp:0.1.378
  namespace: demo
spec:
  selector:
    app:0.1.378
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: app:0.1.378
kind: Deployment
metadata:
  name: demo-webapp:0.1.378
  namespace: demo
  labels:
    app:0.1.378
spec:
  replicas: 1
  selector:
    matchLabels:
      app:0.1.378
  template:
    metadata:
      labels:
        app:0.1.378
    spec:
      containers:
      - name: demo-webapp:0.1.378
        image: gcr.io/$PROJECT_ID/app:0.1.378
        ports:
        - containerPort: 80
