apiVersion: v1
kind: Namespace
metadata: 
  name: demo:0.1.362
---
kind: Service
apiVersion: v1
metadata:
  name: demo:0.1.362
  namespace: demo:0.1.362
spec:
  selector:
    app: demo:0.1.362
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo:0.1.362
  namespace: demo:0.1.362
  labels:
    app: demo:0.1.362
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo:0.1.362
  template:
    metadata:
      labels:
        app: demo:0.1.362
    spec:
      containers:
      - name: demo:0.1.362
        image: gcr.io/sublime-state-352111/demo:0.1.362
        ports:
        - containerPort: 80
